### PR TITLE
Moves the @Component annotation directly to the interface

### PR DESCRIPTION
**Pull request by vogella**
This currently also includes the commit from my other PR but if you dislike the other one, I can remove the change from this PR.

### CODE REVIEW

**Comment by chiuki** [comment]
Good to know that you can directly annotate the interface. I assume the clock module gets overridden by the mock version in the test component, then?

Also, can you remove `.mockClockModule(new MockClockModule())` in `MainActivityTest` for consistency? Thanks!

**Comment by mdelolmo** [comment]
Just for the sake of displaying my support: +1

**Comment by chiuki** [comment]
@vogella Sorry I didn't notice you commited a change right after my comment. It's been a year (!!) and I've changed the repo quite a bit, so I'm not sure how to merge this. I've made a new PR with these changes: #9

**Comment by vogella** [comment]
@chiuki no worries. I close this one.

**Pull request closed without merging**
